module.exports={
    configureWebpack:{
        resolve:{
            alias:{
                "assets":"@/assets",
                "common":"@/common",
                "network":"@/network",
                "components":"@/components",
                "views":"@/views",
            }
        }
    }
}